### ISSUE TITLE
Confusing name/description and App Theme Request

### ISSUE THREAD

**Issue by L1Q** [catppuccin/sharex#1]
The repository seems to contain only ShareX image effect, not a theme. Note that ShareX also supports color themes.
Would be great to clarify what this is and where it's applicable.
An color theme would be a great addition as well!

**Comment by Dukeatron** [comment]
Hey port author here

I am planning to add a complete ShareX **app theme** later in the future when my schedule is cleared out. For now I'll be fixing your specified issue and clarifying it in the README. Thank you for opening the issue!

**Comment by Lucaffo** [comment]
I was bit confused at first as you @L1Q, Catpuccin on all sharex UI could be an explosive looking improvement!

**Comment by Dukeatron** [comment]
Completed by @kingofcube
