### ISSUE TITLE
Sharex

### ISSUE THREAD

**Issue by GrosBourrin** [catppuccin/sharex#2]
doesn't work for sharex, the app doesn"t recognize .sxie files

**Comment by justTOBBI** [comment]
It does for me, are you up to date with your version?

**Comment by GrosBourrin** [comment]
i have sharex 15.0
maybe i put the fle in the wrong folder, could you explain me step by step ? when i'm in the theme section, i ,,do "import but it looks for a json file, not a sxie one

**Comment by Dukeatron** [comment]
The UI theme is being re-worked, kindly to check in after a few days for the updated `.json` files

**Comment by Lavuan** [comment]
any update for `.json` file?

**Comment by Dukeatron** [comment]
Completed, check latest commits
